linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    # - deadcode # deprecated
    - decorder
    # - depguard # unused
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    # - exhaustivestruct # deprecated
    - exhaustruct
    - exportloopref
    # - forbidigo # unused
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    # - golint # deprecated
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    # - ifshort # deprecated
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    # - interfacer # deprecated
    - intrange
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    # - maligned # deprecated
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    # - nosnakecase # deprecated
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    # - scopelint # deprecated
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    # - structcheck # deprecated
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    # - varcheck # deprecated
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
    - zerologlint

linters-settings:
  govet:
    enable-all: true
  misspell:
    locale: US

issues:
  include:
    - EXC0012
    - EXC0014
  exclude-rules:
    - path: _test.go
      linters:
        - revive
      text: "dot-imports:"
    - path: _test\.go
      linters:
        - dupl
        - exhaustruct
        - gochecknoglobals

run:
  allow-parallel-runners: true

output:
  show-stats: true
