---
# Go jobs
- job:
    name: scs-status-page-go-lint
    parent: golangci-lint
    nodeset: pod-fedora-40
    vars:
      golangci_lint_version: 1.60.3
      go_version: 1.23.0
      golangci_lint_options: --timeout 10m

- job:
    name: scs-status-page-go-test
    parent: golang-go
    nodeset: pod-fedora-40
    vars:
      go_command: test ./...
      go_version: 1.23.0

# Container jobs
- job:
    # Build speculative container to check changes.
    name: scs-status-page-build-container-image
    parent: scs-build-container-image
    vars:
      container_images: &status-page-build-container-image
        - context: "."
          container_filename: Containerfile
          registry: registry.scs.community
          repository: registry.scs.community/status-page/status-page-api

- job:
    # Build and upload container to registry.
    name: scs-status-page-upload-container-image
    parent: scs-upload-container-image
    vars:
      upload_container_image_promote: false
      container_images:
        <<: *status-page-build-container-image
        tags:
          - latest
          - "{{ zuul.tag }}"


# Project settings
- project:
    name: SovereignCloudStack/status-page-api
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - scs-status-page-go-lint
        - scs-status-page-go-test
        - scs-status-page-build-container-image
    tag:
      jobs:
        - scs-status-page-upload-container-image
