---
- job:
    name: scs-status-page-go-lint
    parent: golangci-lint
    nodeset:
      nodes:
        - name: ubuntu-jammy
          label: ubuntu-jammy
    vars:
      golangci_lint_version: 1.59.1
      go_version: 1.22.4
      golangci_lint_options: --timeout 5m

- job:
    name: scs-status-page-go-test
    parent: golang-go
    nodeset:
      nodes:
        - name: ubuntu-jammy
          label: ubuntu-jammy
    vars:
      go_command: test ./...
      go_version: 1.22.4

- job:
    name: scs-status-page-go-build
    parent: golang-go
    nodeset:
      nodes:
        - name: ubuntu-jammy
          label: ubuntu-jammy
    vars:
      go_command: build cmd/status-page-api/main.go
      go_version: 1.22.4

- project:
    name: SovereignCloudStack/status-page-api
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - scs-status-page-go-lint
        - scs-status-page-go-test
        - scs-status-page-go-build
