---
- job:
    name: golang-lint
    parent: golangci-lint

- job:
    name: golang-test
    parent: golang-go
    vars:
      go_command: test ./...
      go_version: 1.20.5
- project:
    merge-mode: squash-merge
    default-branch: main
    check:
        jobs:
          - golang-lint
          - golang-test
    check-post:
        jobs:
          - golang-lint
          - golang-test
    gate:
        jobs:
          - golang-lint
          - golang-test
